Semana3/ClaseEnVivo/ProyectoRappi/menuya/delivery/urls.py
from django.urls import path
from . import views


# Create your views here.
app_name = 'delivery'

urlpatterns = [
    path('menu', views.menu, name='menu'),
    path('menulist', views.menulist, name='menulist'),
    path('<int:plato_id>', views.plato, name='plato'),
    path('agregarCarrito/<int:plato_id>', views.agregarCarrito, name='agregarCarrito'),
    path('mostrarCarrito', views.mostrarCarrito, name='mostrarCarrito'),
    path('<int:plato_id>/', views.eliminarCarrito, name='eliminarCarrito'),
    path('', views.limpiarCarrito, name = 'limpiarCarrito'),
    path('loginUsuario', views.loginUsuario, name='loginUsuario'),
    path('registrarCliente', views.registrarCliente, name='registrarCliente'),
    path('registrarPedido', views.registrarPedido, name='registrarPedido'),
    path('gracias', views.gracias, name='gracias'),
    path('confirmarPedido', views.confirmarPedido, name='confirmarPedido')
    
]

Semana3/ClaseEnVivo/ProyectoRappi/menuya/menuya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('delivery.urls')),
    path('theme/', include('theme.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Semana3/ClaseEnVivo/ProyectoRappi/menuya/theme/urls.py
from django.urls import path
from . import views


# Create your views here.
app_name = 'base'

urlpatterns = [
    path('', views.base, name='base')
]

Semana3/ClaseEnVivo/ProyectoRappi/menuya/delivery/models.py
from django.db import models
from django.db.models.deletion import RESTRICT
from django.db.models.fields import CharField
from django.contrib.auth.models import User

# Create your models here.


class Negocio(models.Model):
    nombre = models.CharField(max_length=200)
    imagen = models.ImageField(upload_to='negocios', blank=True, null=True)
    telefono = models.CharField(max_length=50, default='')
    precioEnvio = models.DecimalField(max_digits=9, decimal_places=2)
    calificacion = models.IntegerField(default=0)

    def __str__(self):
        return self.nombre

    ''' class Meta:
        verbose_name_plural = "Negocio" '''


class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    imagen = models.ImageField(upload_to = 'categorias', blank=True, null=True)

    def __str__(self):
        return self.nombre

    ''' class Meta:
        verbose_name_plural = "Categoria" '''


class Plato(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.RESTRICT)
    nombre = CharField(max_length=200)
    imagen = models.ImageField(upload_to='platos', blank=True, null=True)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=9, decimal_places=2)
    negocio = models.ForeignKey(Negocio, on_delete=RESTRICT)

    def __str__(self):
        return self.nombre

    ''' class Meta:
        verbose_name_plural = "Plato" '''

class FormaPago(models.Model):
    nombre = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre
    
class Cliente(models.Model):
    usuario = models.OneToOneField(User,on_delete=models.RESTRICT)
    telefono = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.usuario.first_name} {self.usuario.last_name}"

class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente,on_delete=models.RESTRICT)
    direccion = models.CharField(max_length=200)
    fechaHora = models.DateTimeField(auto_now=True)
    formaPago = models.ForeignKey(FormaPago,on_delete=models.RESTRICT)
    totalPagar = models.DecimalField(max_digits=9,decimal_places=2)
    montoPago = models.DecimalField(max_digits=20,decimal_places=2)

    def __str__(self):
        return self.fechaHora

class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido,on_delete=models.RESTRICT)
    plato = models.ForeignKey(Plato,on_delete=models.RESTRICT)
    precio = models.DecimalField(max_digits=9,decimal_places=2)
    cantidad = models.IntegerField(default=1)

    def __str__(self):
        return self.plato.nombre

Semana3/ClaseEnVivo/ProyectoRappi/menuya/delivery/views.py
from django.shortcuts import redirect, render
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login,logout
# Create your views here.

def menu(request):
    lstCategorias = Categoria.objects.all()
    lstPlatos = Plato.objects.all()
    objNegocio = Negocio.objects.get(pk=1)

    request.session["negocio_telefono"] = objNegocio.telefono
    request.session["negocio_logo"] = objNegocio.imagen.url

    context = {
        'categorias' : lstCategorias,
        'platos' : lstPlatos,


    }

    return render(request, 'menu.html', context)

def menulist(request):
    lstPlatos = Plato.objects.all()

    context = {
        'platos' : lstPlatos
    }
    
    return render(request, 'menu-list.html', context)

def plato(request, plato_id):
    objPlato = Plato.objects.get(pk = plato_id)
    context = {
        'plato' : objPlato
    }

    return render(request, 'plato.html', context)


from .carrito import Cart

def agregarCarrito(request,plato_id):
    objPlato = Plato.objects.get(pk = plato_id)
    cantidad = int(request.POST['cantidad'])
    carrito = Cart(request)
    carrito.add(objPlato, cantidad)
    print(request.session.get("cart"))
    return render(request, 'carrito.html')

def mostrarCarrito(request):
        return render(request, "carrito.html")

def eliminarCarrito(request, plato_id):
    objPlato = Plato.objects.get(pk = plato_id)
    carrito = Cart(request)
    carrito.remove(objPlato)
    return render(request, 'carrito.html')

def limpiarCarrito(request):
    carrito = Cart(request)
    carrito.clear()
    return render(request, 'carrito.html')



def loginUsuario(request):
    context = {}
    if request.method == 'POST':
        dataUsuario = request.POST['usuario']
        dataClave = request.POST['clave']

        print(dataUsuario)

        loginUser= authenticate(request,username=dataUsuario, password=dataClave)
        if loginUser is not None:
            login(request,loginUser)
            return redirect('/registrarPedido')
        else:
            context = {
                'error' : 'datos Incorrectos'
            }

    return render(request, 'loginUsuario.html', context)



def registrarCliente(request):
    if request.method == 'POST':
        #Registrar un nuevo cliente

        dataUsuario = request.POST['usuario']
        dataClave = request.POST['clave']

        nuevoUsuario = User.objects.create_user(username = dataUsuario, password = dataClave)

        nuevoUsuario.first_name = request.POST['nombre']
        nuevoUsuario.last_name = request.POST['apellido']
        nuevoUsuario.email = request.POST['email']

        nuevoUsuario.save()

        nuevoCliente = Cliente(usuario = nuevoUsuario)
        nuevoCliente.telefono = request.POST['telefono']
        nuevoCliente.save()

        
        return redirect('/loginUsuario')
    
    return render(request, "registrarCliente.html")

def registrarPedido(request):
    usuarioPedido = User.get(pk=request.user.id)
    clientePedido = Cliente.objects.get(pk = usuarioPedido)
    print(request.user.id)
    print(request.user.username)

    if request.user.id is not None:
        usuarioPedido = User.objects.get(pk=request.user.id)
        clientePedido = Cliente.objects.get(usuario = usuarioPedido)
        lstFormaPago = FormaPago.objects.all()
        
        context = {
            'nombres' : request.user.first_name,
            'apellidos' : request.user.last_name,
            'telefono' : clientePedido.telefono,
            'email': request.user.email
        }
    else:
        return redirect('/delivery/login')

    return render(request, 'registrarPedido.html', context)

def gracias(request):
    return render(request,'gracias.html')

def confirmarPedido(request):
    if request.method == 'POST':
        #Registro el pedido
        dataFormaPagoId = request.POST['chkFormaPago']
        dataDireccion = request.POST['direccion']
        dataFormaPago = FormaPago.objects.get(pk = dataFormaPagoId)

        nuevoPedido = Pedido(clientePedido)
        nuevoPedido.direccion = dataDireccion
        nuevoPedido.formaPago = dataFormaPago

        nuevoPedido.save()

        return redirect('/delivery/gracias')

Semana3/ClaseEnVivo/ProyectoRappi/menuya/theme/views.py
from django.shortcuts import render

# Create your views here.

def base(request):
    return render(request, 'base.html')

Semana3/ClaseEnVivo/ProyectoRappi/menuya/delivery/templates/index.html
{% extends 'layout.html' %}
{% block content %}
<section class="about-area pd-top-120">
    <div class="container">
        <h3 class="sub-title">BIENVENIDO</h3>
    </div>
</section>
{% endblock %}

Semana3/ClaseEnVivo/ProyectoRappi/menuya/delivery/templates/layout-ligth.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>FoodKa - Food Ordering, Delivery & Restuarent Template</title>
    <!--fivicon icon-->
    <link rel="icon" href="{% static 'assets/img/fevicon.png' %}">

    <!-- Stylesheet -->
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick-slide.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">

    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@300;400;500;600;700;800&family=Bebas+Neue&family=Satisfy&family=Quattrocento:wght@400;700&display=swap" rel="stylesheet">


</head>
<body class='sc5 home-2'>
    <!-- preloader area start -->
    <div class="preloader" id="preloader">
        <div class="preloader-inner">
            <div id="wave1">
            </div>
            <div class="spinner">
                <div class="dot1"></div>
                <div class="dot2"></div>
            </div>
        </div>
    </div>
    <!-- preloader area end -->

    <!-- search popup area start -->
    <div class="body-overlay" id="body-overlay"></div>
    <div class="td-search-popup" id="td-search-popup">
        <form action="index.html" class="search-form">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search.....">
            </div>
            <button type="submit" class="submit-btn"><i class="fa fa-search"></i></button>
        </form>
    </div>
    <!-- //. search Popup -->

    <!-- navbar start -->
    <header class="navbar-area navbar-area-2">
        <nav class="navbar navbar-expand-lg">
            <div class="container nav-container">
                <div class="responsive-mobile-menu">
                    <button class="menu toggle-btn d-block d-lg-none" data-target="#themefie_main_menu" 
                    aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-left"></span>
                        <span class="icon-right"></span>
                    </button>
                </div>
                <div class="logo">
                    <a class="main-logo" href="{% url 'delivery:menu' %}"><img src="{% static 'assets/img//home-2/logo.png' %}" alt="img"></a>
                </div>
                <div class="collapse navbar-collapse" id="themefie_main_menu">
                    <ul class="navbar-nav menu-open">
                        <li class="current-menu-item menu-item-has-children">
                            <a href="home-1.html">HOME</a>
                            <ul class="sub-menu ps-0">
                                <li><a href="home-1.html">Home 01</a></li>
                                <li><a href="home-2.html">Home 02</a></li>
                                <li><a href="home-3.html">Home 03</a></li>
                            </ul>
                        </li>
                        <li class="current-menu-item menu-item-has-children">
                            <a href="#">PAGES</a>
                            <ul class="sub-menu ps-0">
                                <li><a href="about.html">About</a></li>
                                <li><a href="blog.html">Blog</a></li>
                                <li><a href="blog-details.html">Blog Details</a></li>
                                <li><a href="{% url 'delivery:menu' %}">Menu</a></li>
                                <li><a href="{% url 'delivery:menulist' %}">Menu List</a></li>
                                <li><a href="shop.html">Shop</a></li>
                                <li><a href="single-product.html">Shop Details</a></li>
                                <li><a href="cart.html">Cart</a></li>
                                <li><a href="checkout.html">Checkout</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="about.html">ABOUT US</a>
                        </li>
                        <li>
                            <a href="contact.html">CONTACTS</a>
                        </li>
                    </ul>
                </div>
                <div class="nav-right-part nav-right-part-mobile">
                    <ul>
                        <li><a class="search" href="#"><i class="ri-search-line"></i></a>
                        </li>
                        <li class="phone-contact d-md-block d-none"><i class="ri-phone-fill float-start"></i>
                            {{ request.session.negocio_telefono }}
                        </li>
                        <li class="menu-cart"><a href="{% url 'delivery:mostrarCarrito' %}">CART <span>1</span></a></li>
                        <li>49.50 $</li>
                    </ul>
                </div>
                <div class="nav-right-part nav-right-part-desktop">                    
                    <ul>
                        <li class="menu-cart"><a href="{% url 'delivery:mostrarCarrito' %}"><img src="{% static 'assets/img/home-2/icon/shopping-cart.png' %}" alt="icon"> <span>1</span></a></li>
                        <li>49.50 $</li>
                        <li class="phone-contact"><img class="me-2" src="{% static 'assets/img/home-2/icon/phone.png' %}" alt="icon">
                            {{ request.session.negocio_telefono }}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- navbar end -->

    {% block content %}
    {% endblock %}



    <!-- footer area start -->
    <footer class="footer-area-2 pd-top-100">
        <div class="footer-inner padding-top-100 padding-bottom-65">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-sm-6">
                        <div class="footer-widget widget">
                            <div class="logo">
                                <img src="{% static 'assets/img/home-2/logo.png' %}" alt="img">
                            </div>
                            <ul class="contact_info_list">
                                <li class="single-info-item">
                                    <img src="{% static 'assets/img/icon/location.png' %}" alt="icon">
                                    <div class="details">
                                        4920 Trails End Road Ft  United States, FL 33311
                                    </div>
                                </li>
                                <li class="single-info-item">
                                    <img src="{% static 'assets/img/icon/envelope.png' %}" alt="icon">
                                    <div class="details">
                                        ordernow@foodka.com
                                    </div>
                                </li>
                                <li class="single-info-item">
                                    <img src="{% static 'assets/img/icon/phone.png' %}" alt="icon">
                                    <div class="details">
                                        {{ request.session.negocio_telefono }}
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="footer-widget widget widget_link">
                            <h4 class="widget-title">Hot Menu</h4>
                            <ul>
                                <li><a href="menu-list.html">Burger King Whopper</a></li>
                                <li><a href="menu-list.html">Five Guys Cheeseburger</a></li>
                                <li><a href="menu-list.html">KFC Original Recipe Chicken</a></li>
                                <li><a href="menu-list.html">Wendy's Frosty</a></li>
                                <li><a href="menu-list.html">McDonald's Happy Meal</a></li>
                                <li><a href="menu-list.html">Domino's Pepperoni Pizza</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="footer-widget widget widget_link">
                            <h4 class="widget-title">Opening Hours</h4>
                            <ul>
                                <li>Monday : 09.00am-10.00pm</li>
                                <li>Tuesday : 09.00am-10.00pm</li>
                                <li>Wednesday : 09.00am-10.00pm</li>
                                <li>Thursday : 09.00am-10.00pm</li>
                                <li>Friday  : 09.00am-10.00pm</li>
                                <li>Saturday & Sunday : <span>Closed</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="footer-widget widget widget-newsletter">
                            <h4 class="widget-title">Newsletter</h4>
                            <p>Subscribe to get the latest news, update and offer information. Don't worry, we won't send spam!</p>
                            <form class="newsletter-form">
                                <div class="form-group">
                                    <input type="email" placeholder="Enter e-mail">
                                </div>
                                <button class="submit-btn" type="submit"><i class="ri-arrow-right-line"></i></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-md-6 text-md-start text-center">
                        <div class="copyright-area">
                            <p>© 2021 Foodka. All Rights Reserved by Themefie</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <ul class="social-area text-md-end text-center mt-md-0 mt-2">
                            <li><a href="#"><i class="fab fa-facebook-f"></i></a></li> 
                            <li><a href="#"><i class="fab fa-twitter"></i></a></li> 
                            <li><a href="#"><i class="fab fa-behance"></i></a></li> 
                            <li><a href="#"><i class="fab fa-google-plus-g"></i></a></li> 
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer area end -->    

    <!-- back-to-top end -->
    <div class="back-to-top">
        <span class="back-top"><i class="fas fa-angle-double-up"></i></span>
    </div>

    

    <!-- all plugins here -->
    <script src="{% static 'assets/js/jquery.3.6.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/imageloded.min.js' %}"></script>
    <script src="{% static 'assets/js/counterup.js' %}"></script>
    <script src="{% static 'assets/js/waypoint.js' %}"></script>
    <script src="{% static 'assets/js/magnific.min.js' %}"></script>
    <script src="{% static 'assets/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'assets/js/nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/fontawesome.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.min.js' %}"></script>
    <script src="{% static 'assets/js/slick-slider.min.js' %}"></script>
    <script src="{% static 'assets/js/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/tweenmax.min.js' %}"></script>
    <!-- main js  -->
    <script src="{% static 'assets/js/main.js' %}"></script>
</body>
</html>

Semana3/ClaseEnVivo/ProyectoRappi/menuya/delivery/templates/loginUsuario.html
{% extends 'layout-ligth.html' %}
{% block content %}
<div class="checkout-area pd-top-120 pd-bottom-120">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                  </div>
                  {% endif %}
                <div class="bill-payment-wrap">
                    <h5>LOGIN DE USUARIO</h5>
                    <form class="default-form-wrap style-2" action="{% url 'delivery:loginUsuario' %}" method="POST">
                    {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <label>Usuario</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="usuario" class="form-control" placeholder="tu nombre de usuario">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Password</label>
                                <div class="single-input-wrap">
                                    <input type="Password" name="clave" class="form-control" placeholder="tu clave">
                                </div>
                            </div>
                            
                                 <input type="submit" class="btn btn-base" value="INICIAR SESIÓN">
                                 <a href="#" class="btn btn-base">CREAR CUENTA</a>
                            
                        </div>
                    </form>
                </div>                    
            </div>
            
        </div>
    </div>
</div>
{% endblock %}

Semana3/ClaseEnVivo/ProyectoRappi/menuya/delivery/templates/menu.html
{% extends "layout-ligth.html" %}
{% block content %}
{% load static %}
<!-- bredcrumb Area Start-->
<!-- <section class="breadcrumb-area">
    <div class="banner-bg-img"></div>
    <div class="banner-shape-1"><img src="{% static 'assets/img/banner/shape-1.png' %}" alt="img"></div>
    <div class="banner-shape-2"><img src="{% static 'assets/img/banner/shape-2.png' %}" alt="img"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 align-self-center">
                <div class="banner-inner text-center">
                    <h3>Seleccione su pedido
                    </h3>
                    <h1>NUESTRO MENU</h1>
                </div>
            </div>
        </div>
    </div>
</section> -->
<!-- bredcrumb Area End -->

<section class="banner-area banner-area-2">
    <div class="banner-thumb">
        <img src="{% static 'assets/img//home-2/banner/1.png' %}" alt="img">
    </div>
    <div class="banner-bg">
        <div class="banner-bg-img" style="left: -1.95914%; top: -0.475104%;"></div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-8 align-self-center">
                <div class="banner-inner">
                    <h3>Variedad de Sabores!</h3>
                    <h1>Diferentes ingredientes hacen la diferencia</h1>
                    <p>Tenemos lo que tu quieras</p>
                    <a class="btn btn-secondary" href="shop.html">Ordena ahora</a>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- category Area Start-->
<section class="category-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12 align-self-center">
                <ul class="category-menu">
                    {% for cat in categorias %}
                    <li class="category-wrap"><a href="shop.html"><img src="{{ cat.imagen.url }}" alt="category">{{ cat.nombre }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- category Area End -->
<!-- populer Area Start-->
<section class="populer-area pd-top-50 pd-bottom-120">
    <div class="container">
        <div class="row justify-content-center">
        {% for p in platos %}
            <div class="col-lg-4 col-md-6">
                <div class="single-item-wrap">
                    <div class="thumb">
                        <img src="{{ p.imagen.url }}" alt="img">
                        <a class="fav-btn" href="#"><i class="ri-heart-line"></i></a>
                    </div>
                    <div class="wrap-details">
                        <h5><a href="single-product.html">{{ p.nombre }}</a></h5>
                        <div class="wrap-footer">
                            <h6 class="price">S/. {{ p.precio }} </h6>
                        </div>
                    </div>
                    <div class="btn-area">
                        <a class="btn btn-secondary" href="{% url 'delivery:plato' p.id %}">MAS INFO </a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</section>
<!-- populer Area End -->
{% endblock %}

Semana3/ClaseEnVivo/ProyectoRappi/menuya/delivery/templates/registrarCliente.html
{% extends 'layout-ligth.html' %}
{% block content %}
<div class="checkout-area pd-top-120 pd-bottom-120">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="bill-payment-wrap">
                    <h5>REGISTRO DE NUEVO CLIENTE</h5>
                    <form class="default-form-wrap style-2" action="{% url 'delivery:registrarCliente' %}" method="POST">
                    {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <label>Usuario</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="usuario" class="form-control" placeholder="tu nombre de usuario">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Password</label>
                                <div class="single-input-wrap">
                                    <input type="Password" name="clave" class="form-control" placeholder="tu clave">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Nombres</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="nombre" class="form-control" placeholder="Nombres">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Apellidos</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="apellido" class="form-control" placeholder="Apellidos">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Telefono</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="telefono" class="form-control" placeholder="Telefono">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <label>Email</label>
                                <div class="single-input-wrap">
                                    <input type="text" name="email" class="form-control" placeholder="Email">
                                </div>
                            </div>
                            <input type="submit" class="btn btn-base" value="REGISTRAR DATOS">
                        </div>
                    </form>
                </div>                    
            </div>
            
        </div>
    </div>
</div>
{% endblock %}

Semana3/ClaseEnVivo/ProyectoRappi/menuya/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>